/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forms;

/**
 *
 * @author Lucas
 */
public class formPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(formPrincipal.class.getName());

    private formPessoa telaPessoa;
    private formVeiculo telaVeiculo;
    /**
     * Creates new form formPrincipal
     */
    public formPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menu = new javax.swing.JMenuBar();
        menupessoas = new javax.swing.JMenu();
        menuPessoas = new javax.swing.JMenuItem();
        menuveiculos = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        minsair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menupessoas.setText("Calculadoras");

        menuPessoas.setText("Gerenciar Pessoas");
        menuPessoas.addActionListener(this::menuPessoasActionPerformed);
        menupessoas.add(menuPessoas);

        menuveiculos.setText("Gerenciar Veiculos");
        menuveiculos.addActionListener(this::menuveiculosActionPerformed);
        menupessoas.add(menuveiculos);

        menu.add(menupessoas);

        jMenu4.setText("Opções");

        minsair.setText("Sair");
        minsair.addActionListener(this::minsairActionPerformed);
        jMenu4.add(minsair);

        menu.add(jMenu4);

        setJMenuBar(menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuPessoasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPessoasActionPerformed
        // TODO add your handling code here:
         if (telaPessoa == null || !telaPessoa.isDisplayable()) {
        telaPessoa = new formPessoa();
        telaPessoa.setVisible(true);
    } else {
        // Se ela já existe, apenas traz a janela para frente para o usuário ver
        telaPessoa.toFront();
        telaPessoa.requestFocus();
    }
    }//GEN-LAST:event_menuPessoasActionPerformed

    private void menuveiculosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuveiculosActionPerformed
        // TODO add your handling code here:
        //new Form_CalculadorEqSegGrau().setVisible(true);
        if (telaVeiculo == null || !telaVeiculo.isDisplayable()) {
        telaVeiculo = new formVeiculo();
        telaVeiculo.setVisible(true);
    } else {
        // Se ela já existe, apenas traz a janela para frente para o usuário ver
        telaVeiculo.toFront();
        telaVeiculo.requestFocus();
    }
    }//GEN-LAST:event_menuveiculosActionPerformed

    private void minsairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minsairActionPerformed
        // TODO add your handling code here
        System.exit(0);
    }//GEN-LAST:event_minsairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new formPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar menu;
    private javax.swing.JMenuItem menuPessoas;
    private javax.swing.JMenu menupessoas;
    private javax.swing.JMenuItem menuveiculos;
    private javax.swing.JMenuItem minsair;
    // End of variables declaration//GEN-END:variables
}
